services:
  db:
    image: mysql:8.2
    container_name: produto-php_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: produto_php
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"

  app:
    container_name: produto_php_app
    depends_on:
      - db
    build:
      context: .
    ports:
      - 8000:80

volumes:
  db_data:

